// src/App.jsx
import React from 'react'

import Header from './components/layout/Header.jsx'
import Footer from './components/layout/Footer.jsx'
import SideBar from './components/layout/SideBar.jsx'

export default function App({ children }) {
  return (
      <div class="wrapper">
        <Header />
        <SideBar />
        {children}
        <Footer />
      </div>
  )
}

// src/App.vue
<template>
  <div class="app">
    <main-header></main-header>
    <side-bar></side-bar>
    <!-- use router-view element as route outlet -->
    <router-view></router-view>
    <main-footer></main-footer>
  </div>
</template>

<script>
  import store from './vuex/store';

  import MainHeader from './components/layout/Header'
  import SideBar from './components/layout/SideBar'
  import MainFooter from './components/layout/Footer'

  export default {
    name: 'App',
    store: store,
    components:{
      MainHeader,SideBar,MainFooter
    }
  }
</script>
